# Generated by Django 6.0.6 on 2026-07-08 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(
                blank=True, help_text="Leave blank for unlimited", null=True
            ),
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_in", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.event",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("event", "member")},
            },
        ),
    ]
