services:
  - type: web
    name: kafuosa
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hh.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DATABASE_URL
        fromDatabase:
          name: kafuosa-db
          property: connectionString

databases:
  - name: kafuosa-db
    plan: free
