# Generated by Django 6.0.6 on 2026-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("outreach", "Outreach"),
                            ("social", "Social"),
                        ],
                        max_length=20,
                    ),
                ),
                ("excerpt", models.CharField(blank=True, max_length=300)),
                ("body", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="news/"),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
