# Generated by Django 6.0.7 on 2026-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('outreach', 'Outreach'), ('social', 'Social')], default='academic', max_length=20)),
                ('excerpt', models.TextField(max_length=300)),
                ('body', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
