# Generated by Django 6.1.1 on 2026-09-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chairperson', 'Vice Chairperson'), ('secretary', 'Secretary General'), ('asst_secretary', 'Assistant Secretary'), ('treasurer', 'Treasurer'), ('asst_treasurer', 'Assistant Treasurer'), ('academic', 'Academic Secretary'), ('outreach', 'Outreach Coordinator'), ('welfare', 'Welfare Officer'), ('prm', 'PRO & Marketing')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order — lower = first')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officers/')),
                ('short_bio', models.CharField(blank=True, help_text='One line shown on card', max_length=160)),
                ('full_bio', models.TextField(blank=True, help_text='Full bio shown in modal')),
                ('term', models.CharField(blank=True, help_text='e.g. 2025/2026', max_length=50)),
                ('quote', models.CharField(blank=True, max_length=220)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
