# Generated by Django 6.0.6 on 2026-07-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='executives/')),
                ('bio', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide without deleting.')),
            ],
            options={
                'verbose_name': 'Executive Member',
                'verbose_name_plural': 'Executive Council',
                'ordering': ['order', 'name'],
            },
        ),
    ]
