# Generated by Django 6.0.6 on 2026-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Auto-generated or manually assigned member ID', max_length=50, null=True, unique=True),
        ),
    ]
